apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-09-08T15:14:37Z"
  labels:
    app: test-microservices-node-app
  name: test-microservices-node-app
  namespace: default
  resourceVersion: "13151"
  selfLink: /api/v1/namespaces/default/services/test-microservices-node-app
  uid: 5f956f97-d24b-11e9-8756-00155d019101
spec:
  clusterIP: 10.98.142.189
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30781
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: test-microservices-node-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost